reddit<- read.csv('reddit.csv')
str(reddit)
table(reddit$employment.status)
summary(reddit)
levels(reddit$age.range)
library(ggplot2)
qplot(reddit$age.range)
qplot(reddit$income.range)
levels(reddit$income.range)
reddit$age.range=factor(reddit$age.range,levels = c('under 18','18-24','25-34','35-44','45-54','55-64','65 and above'),ordered = T)
qplot(reddit$age.range)
